### ISSUE TITLE
Spacing using inset and outset

### ISSUE THREAD

**Issue by harm-smits** [harm-smits/mesh#2]
**Is your feature request related to a problem? Please describe.**
We should consider adding spacing control in some from. A good example of this could be `space-inset` and `space-outset`. These could have numbered classes for incremental padding around the object by means of `padding`.

**Describe the solution you'd like**
A solution could look like this. Not sure whether I should add them for breakpoints though:
```scss
@for $i from 1 through 4 {
  .mesh-space--inset-#{$i} {
    padding: ($i * .4) + rem;
  }
  .mesh-space--outset-#{$i} {
    margin: ($i * -.4) + rem;
  }
}
```
